Export tree
mariiio/fing-analytics-ml pull request #1
Opened 2019-04-01 23:49 UTC by Matipolle

2019-04-02 21:48 UTC, mariiio requested changes

2019-04-02 21:48 UTC, mariiio commented on fing_analytics_ml/settings.py
> +        'PASSWORD': 'matias4491',
⛔️

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +
Lleno de lineas extra al 💩

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +    print(x)
⛔️

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +    return int(x)
Por que retorna lo que recibe y no mapea a los rangos?

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +    return int(x)
Tambien metiste una indentacion extra?

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +    students = Student.objects.raw('''SELECT grades.Id as id, grades.Year,
indentacion extra?

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +    students = Student.objects.raw('''SELECT grades.Id as id, grades.Year,
🐒

2019-04-02 21:48 UTC, mariiio commented on students_predictions/treebuilder.py
> +    #for i in range(len(nodes)):
⛔️

2019-04-02 21:48 UTC, mariiio commented on students_predictions/treebuilder.py
> +
Doble lineas vacias por todos lados

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +            if not x_train_dict.has_key(modelName):
En vez de `if not` solo `if` y cambiar los bloques?

2019-04-02 21:48 UTC, mariiio commented on students_predictions/predictions.py
> +    '''for model_number in range(1, 5):
⛔️

2019-04-02 21:48 UTC, mariiio commented on students_predictions/treebuilder.py
> +# example exportTree(Model1,feature_names=['Edad','Origen','Educacion','Trabajo','Trabajo software','Cantidad materias','Recursadas','Asistencia teoricos','Asistencia practicos','Grupo','Tiempo dedic
⛔️

2019-04-02 21:56 UTC, mherediaUru commented on fing_analytics_ml/settings.py
> +        'PASSWORD': 'matias4491',
crea las variables de entorno vos bananin

2019-04-02 21:57 UTC, mherediaUru commented on students_predictions/predictions.py
> +    return int(x)
porque no entendimos con chelo porque creaste esos rangos, no sabemos de donde sale, por que razon no usariamos los valores reales y listo?

2019-04-02 22:53 UTC, mariiio requested changes
Sacar los archivos de los modelos del PR

2019-04-02 22:55 UTC, mariiio reviewed
💬

2019-04-02 22:55 UTC, mariiio commented on fing_analytics_ml/settings.py
> +        'PASSWORD': 'matias4491',
jaja si pero no comitees esto igual

2019-04-02 22:55 UTC, mariiio commented on students_predictions/predictions.py
> +    return int(x)
todo tomado el chelo se lo explique como 5 veces

2019-04-03 23:45 UTC, marcelorydel commented on students_predictions/predictions.py
> +    return int(x)
esto es lo que hablamos con libertad el lunes, queda mucho mejor el arbol ademas si ponemos el valor exacto y no un rango

2019-04-05 03:20 UTC, merged